// Code generated by goctl. DO NOT EDIT.

package {{.pkg}}

{{.imports}}

{{.vars}}

// Option 定义选项
type (
    Option  func(*options)
    options struct {
        Session sqlx.Session
    }
)

func WithSession(session sqlx.Session) Option {
    return func(o *options) {
        o.Session = session
    }
}

{{.types}}

{{.new}}

{{.delete}}

{{.find}}

{{.insert}}

{{.update}}

{{.extraMethod}}

{{.tableName}}

{{.customized}}
