// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	model2 "lottery-be/app/model"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	clockTaskRecordFieldNames          = builder.RawFieldNames(&ClockTaskRecord{})
	clockTaskRecordRows                = strings.Join(clockTaskRecordFieldNames, ",")
	clockTaskRecordRowsExpectAutoSet   = strings.Join(stringx.Remove(clockTaskRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	clockTaskRecordRowsWithPlaceHolder = strings.Join(stringx.Remove(clockTaskRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheClockTaskRecordClockTaskRecordIdPrefix = "cache:clockTaskRecord:clockTaskRecord:id:"
)

type (
	clockTaskRecordModel interface {
		Insert(ctx context.Context, data *ClockTaskRecord, opts ...Option) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ClockTaskRecord, error)
		Update(ctx context.Context, data *ClockTaskRecord, opts ...Option) error
		Delete(ctx context.Context, id int64, opts ...Option) error
		Trans(ctx context.Context, fn func(context.Context, sqlx.Session) error) error
	}

	defaultClockTaskRecordModel struct {
		sqlc.CachedConn
		table string
	}

	ClockTaskRecord struct {
		Id               int64     `db:"id"`
		LotteryId        int64     `db:"lottery_id"`        // 抽奖ID
		ClockTaskId      int64     `db:"clock_task_id"`     // 打卡任务ID
		UserId           int64     `db:"user_id"`           // 用户id
		IncreaseMultiple int64     `db:"increase_multiple"` // 概率增加倍数
		DelState         int64     `db:"del_state"`
		CreateTime       time.Time `db:"create_time"`
		UpdateTime       time.Time `db:"update_time"`
	}
)

func newClockTaskRecordModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultClockTaskRecordModel {
	return &defaultClockTaskRecordModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`clock_task_record`",
	}
}

func (m *defaultClockTaskRecordModel) Trans(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultClockTaskRecordModel) Delete(ctx context.Context, id int64, opts ...Option) error {
	// 1. 解析 Options
	var o options
	for _, opt := range opts {
		opt(&o)
	}

	clockTaskRecordClockTaskRecordIdKey := fmt.Sprintf("%s%v", cacheClockTaskRecordClockTaskRecordIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

		// 逻辑分流：判断是否在事务 Session 中执行
		if o.Session != nil {
			return o.Session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, clockTaskRecordClockTaskRecordIdKey)

	return err
}

func (m *defaultClockTaskRecordModel) FindOne(ctx context.Context, id int64) (*ClockTaskRecord, error) {
	clockTaskRecordClockTaskRecordIdKey := fmt.Sprintf("%s%v", cacheClockTaskRecordClockTaskRecordIdPrefix, id)
	var resp ClockTaskRecord
	err := m.QueryRowCtx(ctx, &resp, clockTaskRecordClockTaskRecordIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", clockTaskRecordRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, model2.ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultClockTaskRecordModel) Insert(ctx context.Context, data *ClockTaskRecord, opts ...Option) (sql.Result, error) {
	// 1. 解析 Options
	var o options
	for _, opt := range opts {
		opt(&o)
	}

	// 2. 带缓存模式：利用 m.ExecCtx 保证数据写入后缓存被清理
	clockTaskRecordClockTaskRecordIdKey := fmt.Sprintf("%s%v", cacheClockTaskRecordClockTaskRecordIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, clockTaskRecordRowsExpectAutoSet)

		// 逻辑分流：如果 Options 传入了 Session，则在事务内执行
		if o.Session != nil {
			return o.Session.ExecCtx(ctx, query, data.LotteryId, data.ClockTaskId, data.UserId, data.IncreaseMultiple, data.DelState)
		}
		return conn.ExecCtx(ctx, query, data.LotteryId, data.ClockTaskId, data.UserId, data.IncreaseMultiple, data.DelState)
	}, clockTaskRecordClockTaskRecordIdKey)

	return ret, err
}

func (m *defaultClockTaskRecordModel) Update(ctx context.Context, data *ClockTaskRecord, opts ...Option) error {
	// 1. 解析 Options
	var o options
	for _, opt := range opts {
		opt(&o)
	}

	clockTaskRecordClockTaskRecordIdKey := fmt.Sprintf("%s%v", cacheClockTaskRecordClockTaskRecordIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, clockTaskRecordRowsWithPlaceHolder)

		// 逻辑分流：判断是否在事务 Session 中
		if o.Session != nil {
			return o.Session.ExecCtx(ctx, query, data.LotteryId, data.ClockTaskId, data.UserId, data.IncreaseMultiple, data.DelState, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.LotteryId, data.ClockTaskId, data.UserId, data.IncreaseMultiple, data.DelState, data.Id)
	}, clockTaskRecordClockTaskRecordIdKey)

	return err
}

func (m *defaultClockTaskRecordModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheClockTaskRecordClockTaskRecordIdPrefix, primary)
}

func (m *defaultClockTaskRecordModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", clockTaskRecordRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultClockTaskRecordModel) tableName() string {
	return m.table
}
