// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	clockTaskFieldNames          = builder.RawFieldNames(&ClockTask{})
	clockTaskRows                = strings.Join(clockTaskFieldNames, ",")
	clockTaskRowsExpectAutoSet   = strings.Join(stringx.Remove(clockTaskFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	clockTaskRowsWithPlaceHolder = strings.Join(stringx.Remove(clockTaskFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheClockTaskClockTaskIdPrefix = "cache:clockTask:clockTask:id:"
)

type (
	clockTaskModel interface {
		Insert(ctx context.Context, data *ClockTask, opts ...Option) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ClockTask, error)
		Update(ctx context.Context, data *ClockTask, opts ...Option) error
		Delete(ctx context.Context, id int64, opts ...Option) error
		Trans(ctx context.Context, fn func(context.Context, sqlx.Session) error) error
	}

	defaultClockTaskModel struct {
		sqlc.CachedConn
		table string
	}

	ClockTask struct {
		Id               int64     `db:"id"`
		LotteryId        int64     `db:"lottery_id"`        // 抽奖ID
		Type             int64     `db:"type"`              // 任务类型 1: 体验小程序 2： 浏览指定公众号文章 3: 浏览图片（微信图片二维码等） 4： 浏览视频号视频
		Seconds          int64     `db:"seconds"`           // 任务秒数
		AppletType       int64     `db:"applet_type"`       // type=1时该字段才有意义，1小程序链接 2小程序路径
		PageLink         string    `db:"page_link"`         // type=1 并且 applet_type=1时 该字段才有意义，配置要跳转小程序的页面链接 （如 #小程序://抽奖/oM....）
		AppId            string    `db:"app_id"`            // type=1 并且 applet_type=2时 该字段才有意义，配置要跳转的小程序AppID
		PagePath         string    `db:"page_path"`         // type=1 并且 applet_type=2时 该字段才有意义，配置要跳转的小程序路径（如：/pages/index）
		Image            string    `db:"image"`             // type=3时 该字段才有意义，添加要查看的图片
		VideoAccountId   string    `db:"video_account_id"`  // type=4时 该字段才有意义，视频号ID
		VideoId          string    `db:"video_id"`          // type=4时 该字段才有意义，视频ID
		ArticleLink      string    `db:"article_link"`      // type=2时 该字段才有意义，公众号文章链接
		Copywriting      string    `db:"copywriting"`       // 引导参与者完成打卡任务的文案
		ChanceType       int64     `db:"chance_type"`       // 概率类型 1: 随机 2: 指定
		IncreaseMultiple int64     `db:"increase_multiple"` // chance_type=2时 该字段才有意义，概率增加倍数
		CreateTime       time.Time `db:"create_time"`
		UpdateTime       time.Time `db:"update_time"`
	}
)

func newClockTaskModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultClockTaskModel {
	return &defaultClockTaskModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`clock_task`",
	}
}

func (m *defaultClockTaskModel) Trans(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultClockTaskModel) Delete(ctx context.Context, id int64, opts ...Option) error {
	// 1. 解析 Options
	var o options
	for _, opt := range opts {
		opt(&o)
	}

	clockTaskClockTaskIdKey := fmt.Sprintf("%s%v", cacheClockTaskClockTaskIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

		// 逻辑分流：判断是否在事务 Session 中执行
		if o.Session != nil {
			return o.Session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, clockTaskClockTaskIdKey)

	return err
}

func (m *defaultClockTaskModel) FindOne(ctx context.Context, id int64) (*ClockTask, error) {
	clockTaskClockTaskIdKey := fmt.Sprintf("%s%v", cacheClockTaskClockTaskIdPrefix, id)
	var resp ClockTask
	err := m.QueryRowCtx(ctx, &resp, clockTaskClockTaskIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", clockTaskRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultClockTaskModel) Insert(ctx context.Context, data *ClockTask, opts ...Option) (sql.Result, error) {
	// 1. 解析 Options
	var o options
	for _, opt := range opts {
		opt(&o)
	}

	// 2. 带缓存模式：利用 m.ExecCtx 保证数据写入后缓存被清理
	clockTaskClockTaskIdKey := fmt.Sprintf("%s%v", cacheClockTaskClockTaskIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, clockTaskRowsExpectAutoSet)

		// 逻辑分流：如果 Options 传入了 Session，则在事务内执行
		if o.Session != nil {
			return o.Session.ExecCtx(ctx, query, data.LotteryId, data.Type, data.Seconds, data.AppletType, data.PageLink, data.AppId, data.PagePath, data.Image, data.VideoAccountId, data.VideoId, data.ArticleLink, data.Copywriting, data.ChanceType, data.IncreaseMultiple)
		}
		return conn.ExecCtx(ctx, query, data.LotteryId, data.Type, data.Seconds, data.AppletType, data.PageLink, data.AppId, data.PagePath, data.Image, data.VideoAccountId, data.VideoId, data.ArticleLink, data.Copywriting, data.ChanceType, data.IncreaseMultiple)
	}, clockTaskClockTaskIdKey)

	return ret, err
}

func (m *defaultClockTaskModel) Update(ctx context.Context, data *ClockTask, opts ...Option) error {
	// 1. 解析 Options
	var o options
	for _, opt := range opts {
		opt(&o)
	}

	clockTaskClockTaskIdKey := fmt.Sprintf("%s%v", cacheClockTaskClockTaskIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, clockTaskRowsWithPlaceHolder)

		// 逻辑分流：判断是否在事务 Session 中
		if o.Session != nil {
			return o.Session.ExecCtx(ctx, query, data.LotteryId, data.Type, data.Seconds, data.AppletType, data.PageLink, data.AppId, data.PagePath, data.Image, data.VideoAccountId, data.VideoId, data.ArticleLink, data.Copywriting, data.ChanceType, data.IncreaseMultiple, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.LotteryId, data.Type, data.Seconds, data.AppletType, data.PageLink, data.AppId, data.PagePath, data.Image, data.VideoAccountId, data.VideoId, data.ArticleLink, data.Copywriting, data.ChanceType, data.IncreaseMultiple, data.Id)
	}, clockTaskClockTaskIdKey)

	return err
}

func (m *defaultClockTaskModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheClockTaskClockTaskIdPrefix, primary)
}

func (m *defaultClockTaskModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", clockTaskRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultClockTaskModel) tableName() string {
	return m.table
}
