// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	lotteryParticipationFieldNames          = builder.RawFieldNames(&LotteryParticipation{})
	lotteryParticipationRows                = strings.Join(lotteryParticipationFieldNames, ",")
	lotteryParticipationRowsExpectAutoSet   = strings.Join(stringx.Remove(lotteryParticipationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	lotteryParticipationRowsWithPlaceHolder = strings.Join(stringx.Remove(lotteryParticipationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheLotteryLotteryParticipationIdPrefix              = "cache:lottery:lotteryParticipation:id:"
	cacheLotteryLotteryParticipationLotteryIdUserIdPrefix = "cache:lottery:lotteryParticipation:lotteryId:userId:"
)

type (
	lotteryParticipationModel interface {
		Insert(ctx context.Context, data *LotteryParticipation, opts ...Option) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LotteryParticipation, error)
		FindOneByLotteryIdUserId(ctx context.Context, lotteryId int64, userId int64) (*LotteryParticipation, error)
		Update(ctx context.Context, data *LotteryParticipation, opts ...Option) error
		Delete(ctx context.Context, id int64, opts ...Option) error
		Trans(ctx context.Context, fn func(context.Context, sqlx.Session) error) error
	}

	defaultLotteryParticipationModel struct {
		sqlc.CachedConn
		table string
	}

	LotteryParticipation struct {
		Id         int64     `db:"id"`         // 主键
		LotteryId  int64     `db:"lottery_id"` // 参与的抽奖的id
		UserId     int64     `db:"user_id"`    // 用户id
		IsWon      int64     `db:"is_won"`     // 中奖了吗？
		PrizeId    int64     `db:"prize_id"`   // 中奖id
		DelState   int64     `db:"del_state"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newLotteryParticipationModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultLotteryParticipationModel {
	return &defaultLotteryParticipationModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`lottery_participation`",
	}
}

func (m *defaultLotteryParticipationModel) Trans(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultLotteryParticipationModel) Delete(ctx context.Context, id int64, opts ...Option) error {
	// 1. 解析 Options
	var o options
	for _, opt := range opts {
		opt(&o)
	}

	// 2. 如果存在唯一索引缓存，必须先查出完整数据，否则无法构建所有索引的 Redis Key
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	lotteryLotteryParticipationIdKey := fmt.Sprintf("%s%v", cacheLotteryLotteryParticipationIdPrefix, id)
	lotteryLotteryParticipationLotteryIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheLotteryLotteryParticipationLotteryIdUserIdPrefix, data.LotteryId, data.UserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

		// 逻辑分流：判断是否在事务 Session 中执行
		if o.Session != nil {
			return o.Session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, lotteryLotteryParticipationIdKey, lotteryLotteryParticipationLotteryIdUserIdKey)

	return err
}

func (m *defaultLotteryParticipationModel) FindOne(ctx context.Context, id int64) (*LotteryParticipation, error) {
	lotteryLotteryParticipationIdKey := fmt.Sprintf("%s%v", cacheLotteryLotteryParticipationIdPrefix, id)
	var resp LotteryParticipation
	err := m.QueryRowCtx(ctx, &resp, lotteryLotteryParticipationIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", lotteryParticipationRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLotteryParticipationModel) FindOneByLotteryIdUserId(ctx context.Context, lotteryId int64, userId int64) (*LotteryParticipation, error) {
	lotteryLotteryParticipationLotteryIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheLotteryLotteryParticipationLotteryIdUserIdPrefix, lotteryId, userId)
	var resp LotteryParticipation
	err := m.QueryRowIndexCtx(ctx, &resp, lotteryLotteryParticipationLotteryIdUserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `lottery_id` = ? and `user_id` = ? limit 1", lotteryParticipationRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, lotteryId, userId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLotteryParticipationModel) Insert(ctx context.Context, data *LotteryParticipation, opts ...Option) (sql.Result, error) {
	// 1. 解析 Options
	var o options
	for _, opt := range opts {
		opt(&o)
	}

	// 2. 带缓存模式：利用 m.ExecCtx 保证数据写入后缓存被清理
	lotteryLotteryParticipationIdKey := fmt.Sprintf("%s%v", cacheLotteryLotteryParticipationIdPrefix, data.Id)
	lotteryLotteryParticipationLotteryIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheLotteryLotteryParticipationLotteryIdUserIdPrefix, data.LotteryId, data.UserId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, lotteryParticipationRowsExpectAutoSet)

		// 逻辑分流：如果 Options 传入了 Session，则在事务内执行
		if o.Session != nil {
			return o.Session.ExecCtx(ctx, query, data.LotteryId, data.UserId, data.IsWon, data.PrizeId, data.DelState)
		}
		return conn.ExecCtx(ctx, query, data.LotteryId, data.UserId, data.IsWon, data.PrizeId, data.DelState)
	}, lotteryLotteryParticipationIdKey, lotteryLotteryParticipationLotteryIdUserIdKey)

	return ret, err
}

func (m *defaultLotteryParticipationModel) Update(ctx context.Context, newData *LotteryParticipation, opts ...Option) error {
	// 1. 解析 Options
	var o options
	for _, opt := range opts {
		opt(&o)
	}

	// 2. 如果存在唯一索引缓存，需要先查出旧数据以清理旧索引缓存
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	lotteryLotteryParticipationIdKey := fmt.Sprintf("%s%v", cacheLotteryLotteryParticipationIdPrefix, data.Id)
	lotteryLotteryParticipationLotteryIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheLotteryLotteryParticipationLotteryIdUserIdPrefix, data.LotteryId, data.UserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, lotteryParticipationRowsWithPlaceHolder)

		// 逻辑分流：判断是否在事务 Session 中
		if o.Session != nil {
			return o.Session.ExecCtx(ctx, query, newData.LotteryId, newData.UserId, newData.IsWon, newData.PrizeId, newData.DelState, newData.Id)
		}
		return conn.ExecCtx(ctx, query, newData.LotteryId, newData.UserId, newData.IsWon, newData.PrizeId, newData.DelState, newData.Id)
	}, lotteryLotteryParticipationIdKey, lotteryLotteryParticipationLotteryIdUserIdKey)

	return err
}

func (m *defaultLotteryParticipationModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheLotteryLotteryParticipationIdPrefix, primary)
}

func (m *defaultLotteryParticipationModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", lotteryParticipationRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultLotteryParticipationModel) tableName() string {
	return m.table
}
