// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userFieldNames          = builder.RawFieldNames(&User{})
	userRows                = strings.Join(userFieldNames, ",")
	userRowsExpectAutoSet   = strings.Join(stringx.Remove(userFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userRowsWithPlaceHolder = strings.Join(stringx.Remove(userFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheLooklookUsercenterUserIdPrefix     = "cache:looklookUsercenter:user:id:"
	cacheLooklookUsercenterUserMobilePrefix = "cache:looklookUsercenter:user:mobile:"
)

type (
	userModel interface {
		Insert(ctx context.Context, data *User, opts ...Option) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*User, error)
		FindOneByMobile(ctx context.Context, mobile string) (*User, error)
		Update(ctx context.Context, data *User, opts ...Option) error
		Delete(ctx context.Context, id int64, opts ...Option) error
		Trans(ctx context.Context, fn func(context.Context, sqlx.Session) error) error
	}

	defaultUserModel struct {
		sqlc.CachedConn
		table string
	}

	User struct {
		Id               int64        `db:"id"`
		CreateTime       time.Time    `db:"create_time"`
		UpdateTime       time.Time    `db:"update_time"`
		DeleteTime       sql.NullTime `db:"delete_time"`
		DelState         int64        `db:"del_state"`
		Version          int64        `db:"version"` // 版本号
		Mobile           string       `db:"mobile"`
		Password         string       `db:"password"`
		Nickname         string       `db:"nickname"`
		Sex              int64        `db:"sex"` // 性别 0:男 1:女
		Avatar           string       `db:"avatar"`
		Info             string       `db:"info"`
		IsAdmin          int64        `db:"is_admin"`          // 是否管理员 1是 0否
		Signature        string       `db:"signature"`         // 个性签名
		LocationName     string       `db:"location_name"`     // 地址名称
		Longitude        float64      `db:"longitude"`         // 经度
		Latitude         float64      `db:"latitude"`          // 纬度
		TotalPrize       int64        `db:"total_prize"`       // 累计奖品
		Fans             int64        `db:"fans"`              // 粉丝数量
		AllLottery       int64        `db:"all_lottery"`       // 全部抽奖包含我发起的、我中奖的
		InitiationRecord int64        `db:"initiation_record"` // 发起抽奖记录
		WinningRecord    int64        `db:"winning_record"`    // 中奖记录
	}
)

func newUserModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserModel {
	return &defaultUserModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user`",
	}
}

func (m *defaultUserModel) Trans(ctx context.Context, fn func(context.Context, sqlx.Session) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultUserModel) Delete(ctx context.Context, id int64, opts ...Option) error {
	// 1. 解析 Options
	var o options
	for _, opt := range opts {
		opt(&o)
	}

	// 2. 如果存在唯一索引缓存，必须先查出完整数据，否则无法构建所有索引的 Redis Key
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	looklookUsercenterUserIdKey := fmt.Sprintf("%s%v", cacheLooklookUsercenterUserIdPrefix, id)
	looklookUsercenterUserMobileKey := fmt.Sprintf("%s%v", cacheLooklookUsercenterUserMobilePrefix, data.Mobile)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)

		// 逻辑分流：判断是否在事务 Session 中执行
		if o.Session != nil {
			return o.Session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, looklookUsercenterUserIdKey, looklookUsercenterUserMobileKey)

	return err
}

func (m *defaultUserModel) FindOne(ctx context.Context, id int64) (*User, error) {
	looklookUsercenterUserIdKey := fmt.Sprintf("%s%v", cacheLooklookUsercenterUserIdPrefix, id)
	var resp User
	err := m.QueryRowCtx(ctx, &resp, looklookUsercenterUserIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) FindOneByMobile(ctx context.Context, mobile string) (*User, error) {
	looklookUsercenterUserMobileKey := fmt.Sprintf("%s%v", cacheLooklookUsercenterUserMobilePrefix, mobile)
	var resp User
	err := m.QueryRowIndexCtx(ctx, &resp, looklookUsercenterUserMobileKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `mobile` = ? limit 1", userRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, mobile); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) Insert(ctx context.Context, data *User, opts ...Option) (sql.Result, error) {
	// 1. 解析 Options
	var o options
	for _, opt := range opts {
		opt(&o)
	}

	// 2. 带缓存模式：利用 m.ExecCtx 保证数据写入后缓存被清理
	looklookUsercenterUserIdKey := fmt.Sprintf("%s%v", cacheLooklookUsercenterUserIdPrefix, data.Id)
	looklookUsercenterUserMobileKey := fmt.Sprintf("%s%v", cacheLooklookUsercenterUserMobilePrefix, data.Mobile)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userRowsExpectAutoSet)

		// 逻辑分流：如果 Options 传入了 Session，则在事务内执行
		if o.Session != nil {
			return o.Session.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.Mobile, data.Password, data.Nickname, data.Sex, data.Avatar, data.Info, data.IsAdmin, data.Signature, data.LocationName, data.Longitude, data.Latitude, data.TotalPrize, data.Fans, data.AllLottery, data.InitiationRecord, data.WinningRecord)
		}
		return conn.ExecCtx(ctx, query, data.DeleteTime, data.DelState, data.Version, data.Mobile, data.Password, data.Nickname, data.Sex, data.Avatar, data.Info, data.IsAdmin, data.Signature, data.LocationName, data.Longitude, data.Latitude, data.TotalPrize, data.Fans, data.AllLottery, data.InitiationRecord, data.WinningRecord)
	}, looklookUsercenterUserIdKey, looklookUsercenterUserMobileKey)

	return ret, err
}

func (m *defaultUserModel) Update(ctx context.Context, newData *User, opts ...Option) error {
	// 1. 解析 Options
	var o options
	for _, opt := range opts {
		opt(&o)
	}

	// 2. 如果存在唯一索引缓存，需要先查出旧数据以清理旧索引缓存
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	looklookUsercenterUserIdKey := fmt.Sprintf("%s%v", cacheLooklookUsercenterUserIdPrefix, data.Id)
	looklookUsercenterUserMobileKey := fmt.Sprintf("%s%v", cacheLooklookUsercenterUserMobilePrefix, data.Mobile)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userRowsWithPlaceHolder)

		// 逻辑分流：判断是否在事务 Session 中
		if o.Session != nil {
			return o.Session.ExecCtx(ctx, query, newData.DeleteTime, newData.DelState, newData.Version, newData.Mobile, newData.Password, newData.Nickname, newData.Sex, newData.Avatar, newData.Info, newData.IsAdmin, newData.Signature, newData.LocationName, newData.Longitude, newData.Latitude, newData.TotalPrize, newData.Fans, newData.AllLottery, newData.InitiationRecord, newData.WinningRecord, newData.Id)
		}
		return conn.ExecCtx(ctx, query, newData.DeleteTime, newData.DelState, newData.Version, newData.Mobile, newData.Password, newData.Nickname, newData.Sex, newData.Avatar, newData.Info, newData.IsAdmin, newData.Signature, newData.LocationName, newData.Longitude, newData.Latitude, newData.TotalPrize, newData.Fans, newData.AllLottery, newData.InitiationRecord, newData.WinningRecord, newData.Id)
	}, looklookUsercenterUserIdKey, looklookUsercenterUserMobileKey)

	return err
}

func (m *defaultUserModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheLooklookUsercenterUserIdPrefix, primary)
}

func (m *defaultUserModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserModel) tableName() string {
	return m.table
}
