// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type RegisterReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type SetAdminReq struct {
	Id int64 `json:"id"`
}

type SetAdminResp struct {
}

type User struct {
	Mobile             string  `json:"mobile"`
	Nickname           string  `json:"nickname"`
	Avatar             string  `json:"avatar"`
	Info               string  `json:"info"`
	Signature          string  `json:"signature"`
	Longitude          float64 `json:"longitude"`
	Latitude           float64 `json:"latitude"`
	Id                 int64   `json:"id"`
	Sex                int64   `json:"sex"`
	IsAdmin            int64   `json:"isAdmin"`
	ParticipationCount int64   `json:"participation_count"`
	CreatedCount       int64   `json:"created_count"`
	WonCount           int64   `json:"won_count"`
	Integral           int64   `json:"integral"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	User User `json:"user"`
}

type UserUpdateReq struct {
	Nickname  string  `json:"nickname"`
	Avatar    string  `json:"avatar"`
	Info      string  `json:"info"`
	Signature string  `json:"signature"`
	Longitude float64 `json:"longitude"`
	Latitude  float64 `json:"latitude"`
	Sex       int64
}

type UserUpdateResp struct {
}

type WXMiniAuthReq struct {
	Code          string `json:"code"`
	IV            string `json:"iv"`
	EncryptedData string `json:"encryptedData"`
	Nickname      string `json:"nickname, optional"`
	Avatar        string `json:"avatar, optional"`
}

type WXMiniAuthResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}
