// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: lottery.proto

package server

import (
	"context"
	pb2 "lottery-be/app/lottery/cmd/rpc/pb"

	"lottery-be/app/lottery/cmd/rpc/internal/logic"
	"lottery-be/app/lottery/cmd/rpc/internal/svc"
)

type LotteryServer struct {
	svcCtx *svc.ServiceContext
	pb2.UnimplementedLotteryServer
}

func NewLotteryServer(svcCtx *svc.ServiceContext) *LotteryServer {
	return &LotteryServer{
		svcCtx: svcCtx,
	}
}

// -----------------------抽奖表-----------------------
func (s *LotteryServer) AddLottery(ctx context.Context, in *pb2.AddLotteryReq) (*pb2.AddLotteryResp, error) {
	l := logic.NewAddLotteryLogic(ctx, s.svcCtx)
	return l.AddLottery(in)
}

func (s *LotteryServer) UpdateLottery(ctx context.Context, in *pb2.UpdateLotteryReq) (*pb2.UpdateLotteryResp, error) {
	l := logic.NewUpdateLotteryLogic(ctx, s.svcCtx)
	return l.UpdateLottery(in)
}

func (s *LotteryServer) DelLottery(ctx context.Context, in *pb2.DelLotteryReq) (*pb2.DelLotteryResp, error) {
	l := logic.NewDelLotteryLogic(ctx, s.svcCtx)
	return l.DelLottery(in)
}

func (s *LotteryServer) GetLotteryById(ctx context.Context, in *pb2.GetLotteryByIdReq) (*pb2.GetLotteryByIdResp, error) {
	l := logic.NewGetLotteryByIdLogic(ctx, s.svcCtx)
	return l.GetLotteryById(in)
}

func (s *LotteryServer) SearchLottery(ctx context.Context, in *pb2.SearchLotteryReq) (*pb2.SearchLotteryResp, error) {
	l := logic.NewSearchLotteryLogic(ctx, s.svcCtx)
	return l.SearchLottery(in)
}

func (s *LotteryServer) SetIsSelectedLottery(ctx context.Context, in *pb2.SetIsSelectedLotteryReq) (*pb2.SetIsSelectedLotteryResp, error) {
	l := logic.NewSetIsSelectedLotteryLogic(ctx, s.svcCtx)
	return l.SetIsSelectedLottery(in)
}

func (s *LotteryServer) LotteryDetail(ctx context.Context, in *pb2.LotteryDetailReq) (*pb2.LotteryDetailResp, error) {
	l := logic.NewLotteryDetailLogic(ctx, s.svcCtx)
	return l.LotteryDetail(in)
}

func (s *LotteryServer) LotterySponsor(ctx context.Context, in *pb2.LotterySponsorReq) (*pb2.LotterySponsorResp, error) {
	l := logic.NewLotterySponsorLogic(ctx, s.svcCtx)
	return l.LotterySponsor(in)
}

func (s *LotteryServer) AnnounceLottery(ctx context.Context, in *pb2.AnnounceLotteryReq) (*pb2.AnnounceLotteryResp, error) {
	l := logic.NewAnnounceLotteryLogic(ctx, s.svcCtx)
	return l.AnnounceLottery(in)
}

func (s *LotteryServer) CheckUserCreatedLottery(ctx context.Context, in *pb2.CheckUserCreatedLotteryReq) (*pb2.CheckUserCreatedLotteryResp, error) {
	l := logic.NewCheckUserCreatedLotteryLogic(ctx, s.svcCtx)
	return l.CheckUserCreatedLottery(in)
}

func (s *LotteryServer) CheckUserCreatedLotteryAndToday(ctx context.Context, in *pb2.CheckUserCreatedLotteryAndTodayReq) (*pb2.CheckUserCreatedLotteryAndTodayResp, error) {
	l := logic.NewCheckUserCreatedLotteryAndTodayLogic(ctx, s.svcCtx)
	return l.CheckUserCreatedLotteryAndToday(in)
}

func (s *LotteryServer) CheckUserCreatedLotteryAndThisWeek(ctx context.Context, in *pb2.CheckUserCreatedLotteryAndThisWeekReq) (*pb2.CheckUserCreatedLotteryAndThisWeekResp, error) {
	l := logic.NewCheckUserCreatedLotteryAndThisWeekLogic(ctx, s.svcCtx)
	return l.CheckUserCreatedLotteryAndThisWeek(in)
}

func (s *LotteryServer) GetLotteryListAfterLogin(ctx context.Context, in *pb2.GetLotteryListAfterLoginReq) (*pb2.GetLotteryListAfterLoginResp, error) {
	l := logic.NewGetLotteryListAfterLoginLogic(ctx, s.svcCtx)
	return l.GetLotteryListAfterLogin(in)
}

func (s *LotteryServer) GetLotteryStatistic(ctx context.Context, in *pb2.GetLotteryStatisticReq) (*pb2.GetLotteryStatisticResp, error) {
	l := logic.NewGetLotteryStatisticLogic(ctx, s.svcCtx)
	return l.GetLotteryStatistic(in)
}

func (s *LotteryServer) GetLotteryListLastId(ctx context.Context, in *pb2.GetLotteryListLastIdReq) (*pb2.GetLotteryListLastIdResp, error) {
	l := logic.NewGetLotteryListLastIdLogic(ctx, s.svcCtx)
	return l.GetLotteryListLastId(in)
}

func (s *LotteryServer) PublishLottery(ctx context.Context, in *pb2.PublishLotteryReq) (*pb2.PublishLotteryResp, error) {
	l := logic.NewPublishLotteryLogic(ctx, s.svcCtx)
	return l.PublishLottery(in)
}

func (s *LotteryServer) GetLotteryPrizesListByUserId(ctx context.Context, in *pb2.GetLotteryPrizesListByUserIdReq) (*pb2.GetLotteryPrizesListByUserIdResp, error) {
	l := logic.NewGetLotteryPrizesListByUserIdLogic(ctx, s.svcCtx)
	return l.GetLotteryPrizesListByUserId(in)
}

// -----------------------奖品表-----------------------
func (s *LotteryServer) AddPrize(ctx context.Context, in *pb2.AddPrizeReq) (*pb2.AddPrizeResp, error) {
	l := logic.NewAddPrizeLogic(ctx, s.svcCtx)
	return l.AddPrize(in)
}

func (s *LotteryServer) UpdatePrize(ctx context.Context, in *pb2.UpdatePrizeReq) (*pb2.UpdatePrizeResp, error) {
	l := logic.NewUpdatePrizeLogic(ctx, s.svcCtx)
	return l.UpdatePrize(in)
}

func (s *LotteryServer) DelPrize(ctx context.Context, in *pb2.DelPrizeReq) (*pb2.DelPrizeResp, error) {
	l := logic.NewDelPrizeLogic(ctx, s.svcCtx)
	return l.DelPrize(in)
}

func (s *LotteryServer) GetPrizeById(ctx context.Context, in *pb2.GetPrizeByIdReq) (*pb2.GetPrizeByIdResp, error) {
	l := logic.NewGetPrizeByIdLogic(ctx, s.svcCtx)
	return l.GetPrizeById(in)
}

func (s *LotteryServer) SearchPrize(ctx context.Context, in *pb2.SearchPrizeReq) (*pb2.SearchPrizeResp, error) {
	l := logic.NewSearchPrizeLogic(ctx, s.svcCtx)
	return l.SearchPrize(in)
}

func (s *LotteryServer) GetPrizeListByLotteryId(ctx context.Context, in *pb2.GetPrizeListByLotteryIdReq) (*pb2.GetPrizeListByLotteryIdResp, error) {
	l := logic.NewGetPrizeListByLotteryIdLogic(ctx, s.svcCtx)
	return l.GetPrizeListByLotteryId(in)
}

// -----------------------参与抽奖-----------------------
func (s *LotteryServer) AddLotteryParticipation(ctx context.Context, in *pb2.AddLotteryParticipationReq) (*pb2.AddLotteryParticipationResp, error) {
	l := logic.NewAddLotteryParticipationLogic(ctx, s.svcCtx)
	return l.AddLotteryParticipation(in)
}

func (s *LotteryServer) SearchLotteryParticipation(ctx context.Context, in *pb2.SearchLotteryParticipationReq) (*pb2.SearchLotteryParticipationResp, error) {
	l := logic.NewSearchLotteryParticipationLogic(ctx, s.svcCtx)
	return l.SearchLotteryParticipation(in)
}

func (s *LotteryServer) GetParticipationUserIdsByLotteryId(ctx context.Context, in *pb2.GetParticipationUserIdsByLotteryIdReq) (*pb2.GetParticipationUserIdsByLotteryIdResp, error) {
	l := logic.NewGetParticipationUserIdsByLotteryIdLogic(ctx, s.svcCtx)
	return l.GetParticipationUserIdsByLotteryId(in)
}

func (s *LotteryServer) CheckIsParticipated(ctx context.Context, in *pb2.CheckIsParticipatedReq) (*pb2.CheckIsParticipatedResp, error) {
	l := logic.NewCheckIsParticipatedLogic(ctx, s.svcCtx)
	return l.CheckIsParticipated(in)
}

func (s *LotteryServer) GetSelectedLotteryStatistic(ctx context.Context, in *pb2.GetSelectedLotteryStatisticReq) (*pb2.GetSelectedLotteryStatisticResp, error) {
	l := logic.NewGetSelectedLotteryStatisticLogic(ctx, s.svcCtx)
	return l.GetSelectedLotteryStatistic(in)
}

func (s *LotteryServer) CheckSelectedLotteryParticipated(ctx context.Context, in *pb2.CheckSelectedLotteryParticipatedReq) (*pb2.CheckSelectedLotteryParticipatedResp, error) {
	l := logic.NewCheckSelectedLotteryParticipatedLogic(ctx, s.svcCtx)
	return l.CheckSelectedLotteryParticipated(in)
}

func (s *LotteryServer) CheckUserIsWon(ctx context.Context, in *pb2.CheckUserIsWonReq) (*pb2.CheckUserIsWonResp, error) {
	l := logic.NewCheckUserIsWonLogic(ctx, s.svcCtx)
	return l.CheckUserIsWon(in)
}

func (s *LotteryServer) GetWonList(ctx context.Context, in *pb2.GetWonListReq) (*pb2.GetWonListResp, error) {
	l := logic.NewGetWonListLogic(ctx, s.svcCtx)
	return l.GetWonList(in)
}

func (s *LotteryServer) GetWonListCount(ctx context.Context, in *pb2.GetWonListCountReq) (*pb2.GetWonListCountResp, error) {
	l := logic.NewGetWonListCountLogic(ctx, s.svcCtx)
	return l.GetWonListCount(in)
}

func (s *LotteryServer) GetWonListByLotteryId(ctx context.Context, in *pb2.GetWonListByLotteryIdReq) (*pb2.GetWonListByLotteryIdResp, error) {
	l := logic.NewGetWonListByLotteryIdLogic(ctx, s.svcCtx)
	return l.GetWonListByLotteryId(in)
}

// -----------------------完成打卡任务-----------------------
func (s *LotteryServer) AddClockTaskRecord(ctx context.Context, in *pb2.AddClockTaskRecordReq) (*pb2.AddClockTaskRecordResp, error) {
	l := logic.NewAddClockTaskRecordLogic(ctx, s.svcCtx)
	return l.AddClockTaskRecord(in)
}
